### ISSUE TITLE
Links to Colorbook project and GitHub are switched on Colorbook page

### ISSUE THREAD

**Issue by sambehrens** [liyasthomas/liyasthomas#10]
# Expected Behavior

Link to "View Project ->" should take you to https://liyasthomas.github.io/colorbook/

Link to "GitHub" should take you to https://github.com/liyasthomas/colorbook

# Current Behavior

Link to "View Project ->" takes you to https://github.com/liyasthomas/colorbook

Link to "GitHub" takes you to https://liyasthomas.github.io/colorbook/

## Steps to Reproduce

Go to https://liyasthomas.web.app/project/colorbook

Click on the "View Project ->" button and the "GitHub" button.

Notice how they take you to the opposite pages.

**Comment by liyasthomas** [comment]
My bad, will fix it ASAP
