### ISSUE TITLE
Web Share API

### ISSUE THREAD

**Issue by stephenajulu** [liyasthomas/liyasthomas#21]
Hi, how are you? I would like to know how you implemented your web share.

**Comment by liyasthomas** [comment]
There are lot of online tutorials available online. All are pretty easy to implement and efficient. Few of my favorites are:
- https://web.dev/web-share
- https://css-tricks.com/how-to-use-the-web-share-api/
- https://alligator.io/js/web-share-api/

*Do checkout it's browser support:* https://caniuse.com/#feat=web-share
